databases:
  - name: bloodtracker
    plan: free
    databaseName: bloodtracker
    user: bloodtracker
    region: frankfurt

services:
  - type: web
    plan: free
    name: bloodtracker
    env: ruby
    region: frankfurt
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bloodtracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false